version: '3'
services:
  profile:
    build:
      context: .
      dockerfile: ./profile/Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - "mongo"
  tweet: 
    build:
      context: .
      dockerfile: ./tweet/Dockerfile
    ports:
    - "8081:8081"
    depends_on:
    - "mongo"
    - "redis"
  social: 
    build:
      context: .
      dockerfile: ./social/Dockerfile
    ports:
    - "8082:8082"
    depends_on:
    - "mongo"
    - "redis"
    - "neo4jdb"
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    command: redis-server --requirepass SomePassword1234
    logging:
      driver: "none"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tweetzer
      - MONGO_INITDB_ROOT_PASSWORD=SomePassword1234
      - MONGO_ROOT_USER=tweetzer
      - MONGO_ROOT_PASS=SomePassword1234
      - APP_MONGO_USER=tweetzer
      - APP_MONGO_PASS=SomePassword1234
      - APP_MONGO_DB=glimpse
    volumes:
      - $HOME/mongod:/data/db
    logging:
      driver: "none"
  neo4jdb:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/abc
    logging:
      driver: "none"