version: '3'
services:
  profile:
    build:
      context: .
      dockerfile: ./profile/Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - "mongo"
  tweet: 
    build:
      context: .
      dockerfile: ./tweet/Dockerfile
    ports:
    - "8081:8081"
    depends_on:
    - "mongo"
    - "redis"
  social: 
    build:
      context: .
      dockerfile: ./social/Dockerfile
    ports:
    - "8083:8083"
    depends_on:
    - "mongo"
    - "redis"
    - "neo4jdb"
  nodejs:
    image: node:latest
    volumes:
      - ../frontend:/home/web
    working_dir: /home/web
    command: npm install
    command: npm run-script build
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    command: redis-server --requirepass SomePassword1234
    logging:
      driver: "json-file"
  nginx:
    image: nginx
    volumes:
      - ../frontend/build/:/home/web/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=tweetzer.com
      - NGINX_PORT=80
    depends_on:
    - "nodejs"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tweetzer
      - MONGO_INITDB_ROOT_PASSWORD=SomePassword1234
      - MONGO_ROOT_USER=tweetzer
      - MONGO_ROOT_PASS=SomePassword1234
      - APP_MONGO_USER=tweetzer
      - APP_MONGO_PASS=SomePassword1234
      - APP_MONGO_DB=tweetzer
    volumes:
      - $HOME/mongod:/data/db
    logging:
      driver: "json-file"
  neo4jdb:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/abc
    logging:
      driver: "json-file"